### ISSUE TITLE
🐛 [BUG] : Realtime Websocket Idling

### ISSUE THREAD

**Issue by xuelink** [langx/langx#366]
**To Reproduce**
1. Build android simulator in android studio
2. Register new user
3. Start new chat
4. Send a msg
5. 🐛 [BUG] : not showing
6. Send another
7. 🐛 [BUG] : not showing
8. go back
9. click messages
10. 🐛 [BUG] : room created but there is no messages
11. refresh
12. everything fine.

**Screenshots**

https://github.com/languageXchange/languageXchange/assets/3280475/fb4ee012-bb5b-48ac-93b7-fcda17106aab

**Comment by behics** [comment]
This is related with websocket issue, appwrite realtime socket stops working, clearing channels, not closing wss. 

@ibrahimsag got info about it

**Comment by behics** [comment]
> I recommend to drop appwrite realtime and use ajax, It use websocket under the hood. Not so good for mobile
> https://github.com/react-declarative/nestjs-appwrite-bff
> problem-solver for websocket
> webhook+rxjs+sockjs

**Comment by behics** [comment]
https://rxjs.dev/api/webSocket/webSocket

**Comment by behics** [comment]
@tripolskypetr I was not aware that there was an issue on the server side. Can you share what led you to believe socket stability issues are connected the nestjs-appwrite-bff?

**Comment by behics** [comment]
Opened a issue in appwrite support: appwrite/sdk-for-web#91

**Comment by behics** [comment]
> Opened a issue in appwrite support: [appwrite/sdk-for-web#91](https://github.com/appwrite/sdk-for-web/issues/91)

They raised that issue about 2weeks ago, appwrite/appwrite#7584

**Comment by behics** [comment]
Related discord thread: https://discord.com/channels/564160730845151244/1201047679338295429

**Comment by xuelink** [comment]
It still continues. Fixed with patched version of appwrite fixed the issue about closing socket manually but it didnt solve it following issue @ibrahimsag 

> The problem arises when there's a period of inactivity on the real-time socket. During this time, the socket stops sending any data. It behaves as if the connection has dropped, but it doesn't actually close the connection. The socket appears to be active but doesn't transmit any information.

Discord thread about it: https://discord.com/channels/564160730845151244/1223009717526331622/1223009717526331622

https://github.com/languageXchange/languageXchange/assets/3280475/5c5912a5-f621-4315-83ff-7742468fdf32

**Comment by xuelink** [comment]
Cloudflare is fixed it most of the cases, lets `test` it before we close it, if you see similar error please comment down.

**Comment by xuelink** [comment]
If we will get any report of this issue, we will open it. Now closing..
