### ISSUE TITLE
🚀 [Feature] : Improve Chat UI

### ISSUE THREAD

**Issue by xuelink** [langx/langx#399]
Should be fixed
- [x] Refreshing Issues
- [x] Merge ChatBoxComponent and PreChatBoxComponent (related w/ #514)
  - [x] #634
- [x] Smooth scrollToBottom
- [x] Can Copy
- [x] #468
- [x] #366

Additionally
- [x] #457
- [x] #507
- [x] #605
- [ ] #622
- [x] #612
- [ ] #613

**Comment by behics** [comment]
b7d3ab6aaa3e1464b133f822411572cc44358e1a

**Comment by behics** [comment]
can copy: https://github.com/languageXchange/languageXchange/commit/7fb0031693709f8da2df8bddc8546f0201274566

**Comment by xuelink** [comment]
Most of the outstanding features are completed, others are linked with new issue, so its done here.
