### ISSUE TITLE
⚠ [Warning] : Use default system browser

### ISSUE THREAD

**Issue by oneofvalts** [langx/langx#435]
On Android, when trying to log in with Google, looks like a custom browser opens up instead of the default system browser. This prevents password managers or saved passwords.

Also, in the Google authentication screen, "Device" is shown as "CPU iPhone OS16_5_1 like Mac OS X", which is a bit intimidating.

Using the default system browser would be more appropriate.

**Comment by behics** [comment]
Yes you are right, it should be fixed!

**Comment by behics** [comment]
We love PR ❤️

If you want to contribute, i can assign this issue to you 😅

**Comment by oneofvalts** [comment]
Well, I am a complete beginner in TypeScript and all, but if you could point me where to start looking at, I can give it a try :) @behics

**Comment by behics** [comment]
Thank you for your intent! :)

**Comment by xuelink** [comment]
https://github.com/langx/langx/assets/3280475/0ac80c52-d34e-4086-8061-551c2971ec26

_Contributor: @korblen from Discord_

**Comment by xuelink** [comment]
> It shows I'm login on iOS but my phone is a Google Pixel

Another issue here 

_Contributor: @DH-555_

**Comment by xuelink** [comment]
https://pub.dev/packages/flutter_web_auth

**Comment by xuelink** [comment]
It's fixed with RN version.
