### ISSUE TITLE
🚀 [Feature] : Second Mother Language / Other Languages

### ISSUE THREAD

**Issue by xuelink** [langx/langx#438]
If you want this feature, please send emoji to the issue to speed up this process.

Detailed here : https://github.com/langxapp/langx/issues/438#issuecomment-2050488098

**Comment by nesrincetinn** [comment]
![IMG_7711](https://github.com/languageXchange/languageXchange/assets/160430614/e148550f-f124-4ad9-af79-bf6fb02bc939)

**Comment by behics** [comment]
- [ ] And add section "language I speak"

**Comment by pizofreude** [comment]
> * [ ]  And add section "language I speak"

[] "language(s) I speak would be preferable since many of the members I saw today are polyglots.

**Comment by behics** [comment]
> > * [ ]   And add section "language I speak"
> 
> [] "language(s) I speak" would be preferable since many of the members I saw today are polyglots.

Yes most of the early-adoptors of us are polyglots :) i will make this issue prioritized and hopefullt do it for the next release.

**Comment by xuelink** [comment]
@pastanton You also can upvote here instead of #645 or follow this issue. Also you can add your comment here ;)

Better to have only one issue to track this process easily ;) 

Thank you for your understanding

**Comment by xuelink** [comment]
<img width="746" alt="Screenshot 2024-04-18 at 11 14 10 PM" src="https://github.com/langx/langx/assets/3280475/6e1361fa-8871-4990-a967-afaffa473b66">

_Contributor: Diana from Canada 🇨🇦_

**Comment by xuelink** [comment]
<img width="1030" alt="Screenshot 2024-05-03 at 7 11 17 PM" src="https://github.com/langx/langx/assets/3280475/b675e084-40b0-4805-b15d-a359a05d0a1b">
