### ISSUE TITLE
🐛 [BUG] : Empty Chat Page

### ISSUE THREAD

**Issue by xuelink** [langx/langx#468]
We need reproduction steps for this bug.

- [x] Send msg and before its delivered click back and try to open another room
- [x] After taping the notification..

![IMG_8140](https://github.com/languageXchange/languageXchange/assets/3280475/ddd26aef-b84a-48eb-9020-a285ad867b83)
![IMG_8138](https://github.com/languageXchange/languageXchange/assets/3280475/dc9d138f-626a-4b0a-bb6a-c17cb14662e9)

**Comment by nesrincetinn** [comment]
![IMG_7709](https://github.com/languageXchange/languageXchange/assets/160430614/ed87a1eb-906b-4d9c-bf65-4ff6f6e61857)

**Comment by behics** [comment]
![WhatsApp Image 2024-02-20 at 12 53 08 AM](https://github.com/languageXchange/languageXchange/assets/3280475/202939f9-dae2-4202-bab2-2a9f1aa2416b)

**Comment by xuelink** [comment]
![group-21457946-84144163-photo](https://github.com/langxapp/langx/assets/3280475/07778fd6-c82b-4319-b390-ff4ebabc6bc2)

**Comment by xuelink** [comment]
![IMG_9302](https://github.com/langxapp/langx/assets/3280475/020e6b50-5e48-4eb0-b15f-ff13d6284740)

**Comment by xuelink** [comment]
When i tap in the notification, i can see this page again.

![IMG_9380](https://github.com/langxapp/langx/assets/3280475/2b2526b5-c06a-46c2-b942-a22be2290d0b)

**Comment by xuelink** [comment]
<img width="446" alt="Screenshot 2024-04-20 at 7 42 35 PM" src="https://github.com/langx/langx/assets/3280475/2f35f36a-e169-485e-82c6-216b78f7200e">

**Comment by xuelink** [comment]
![image](https://github.com/langx/langx/assets/3280475/2af2a3f6-41b8-43c5-9a6c-c021b93985d7)

**Comment by xuelink** [comment]
Done with RN version.
