### ISSUE TITLE
🐛 [BUG] : Birthdate condition check while signin up

### ISSUE THREAD

**Issue by xuelink** [langx/langx#474]
7yo registered user is absolutely a bug!

<img width="264" alt="Screenshot 2024-02-19 at 2 26 29 PM" src="https://github.com/languageXchange/languageXchange/assets/3280475/df354171-bfd8-4bab-b366-69a2e60a6306">

**Comment by behics** [comment]
> the app asks for the user's email and password first, then it asks for the user's birth date, gender etc. Underneath there's a small disclaimer that the user cannot continue if under 13 years old

> if that's the case it is better to ask for the user's age before they enter their info such as their email and password 

@itztess

**Comment by xuelink** [comment]
<img width="694" alt="303376253-58dd2944-ebad-4237-8015-fe2e126b1579" src="https://github.com/langxapp/langx/assets/3280475/57c60bfc-9d27-4254-8994-7766dfd6b047">

**Comment by xuelink** [comment]
<img width="1065" alt="Screenshot_2024-04-18_at_3 25 14_AM" src="https://github.com/langxapp/langx/assets/3280475/c8d9085f-e98a-45e0-bd1b-ef5d9ae59ff3">

**Comment by xuelink** [comment]
![image](https://github.com/langx/langx/assets/3280475/6172702e-6e0a-45f9-969a-9ab8b9afceec)

**Comment by xuelink** [comment]
![image](https://github.com/langx/langx/assets/3280475/bc8b8e5e-fb25-479e-8ed5-8e53f13d83bf)

**Comment by xuelink** [comment]
![image](https://github.com/langx/langx/assets/3280475/cc4e4124-af90-4f6a-9a85-4478184a5510)

**Comment by xuelink** [comment]
It's fixed with RN version.
