### ISSUE TITLE
🚀 [Feature] : Search Feature

### ISSUE THREAD

**Issue by xuelink** [langx/langx#476]
**Is your feature request related to a problem? Please describe.**
Next to the filter button, we need seach feature as well.

**Describe the solution you'd like**
Its hard to find exactly a user by `name`.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by pizofreude** [comment]
@behics will the search exact user by username/name be added or is this abandoned?

**Comment by behics** [comment]
yes it should be

**Comment by pizofreude** [comment]
Thanks, I'll link this into my new related feature request. Stay tuned.

**Comment by xuelink** [comment]
Related with #715
