### ISSUE TITLE
🚀 [Feature] : Filter By Exact Language

### ISSUE THREAD

**Issue by xuelink** [langx/langx#488]
**Is your feature request related to a problem? Please describe.**
> If can I suggest, maybe could be useful exist some kind of filter to find who want to practice or learn my language.

**Describe the solution you'd like**
Filter by only exact language that you choose.

Related: #476 

_Contributor: Laurent from Brazil 🇧🇷_ 

**Checklist**
- [ ] #488
- [ ] #438
- [ ] #493
- [x] #246 
- [ ] #265

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by behics** [comment]
<img width="457" alt="Screenshot 2024-03-05 at 1 31 09 PM" src="https://github.com/languageXchange/languageXchange/assets/3280475/b3663b35-68a6-4b3e-9aa4-4b5c3bf3b91c">

**Comment by xuelink** [comment]
Requested again.
> btw is there a way to look for people who are learning your fluent language
that would be a cool feature

**Comment by xuelink** [comment]
![image](https://github.com/langx/langx/assets/3280475/a434c95a-257a-4079-9465-40e987c31ecc)

**Comment by xuelink** [comment]
<img width="561" alt="Screenshot 2024-04-26 at 1 56 58 PM" src="https://github.com/langx/langx/assets/3280475/44bd82d4-cc29-48b6-96a7-12222d39e023">
@karine8291 from Discord

**Comment by xuelink** [comment]
![image](https://github.com/langx/langx/assets/3280475/fed593ea-f35a-4370-af42-e68a1dd70b9a)

**Comment by xuelink** [comment]
<img width="616" alt="Screenshot 2024-05-03 at 7 04 13 PM" src="https://github.com/langx/langx/assets/3280475/47092171-2a8e-42e3-b2d8-bc58a9a01cec">

**Comment by skfh82** [comment]
Instead of exact filter, exact language pair matches could be sorted to the top. Then the less exact matches could appear after, to deal with the problem of mismatched target languages.

**Comment by xuelink** [comment]
> Instead of exact filter, exact language pair matches could be sorted to the top. Then the less exact matches could appear after, to deal with the problem of mismatched target languages.

Thank you to rise this issue again, we are planning to implement it to our app exactly as you suggested above, `For You` section will show you exact language that you are trying to practice and matches perfect language partner. Secondly, when we will be at the time that we are termination our [early-adopter](https://docs.langx.io/litepaper/welcome/badges#early-adopter-badge) badge then we are planning not to show all users to everyone to decrease unwanted noises :)

By the way, check your mailbox, i just invited you to join our organization here :)

Best

**Comment by xuelink** [comment]
<img width="1165" alt="Screenshot_2024-06-07_at_6 33 37_PM" src="https://github.com/langx/langx/assets/3280475/2cbd5ede-0a57-4426-b31e-087d7c71775e">

sad but its ok ! :)
