### ISSUE TITLE
🚀 [Feature] : Add Absolute Beginner Language Level

### ISSUE THREAD

**Issue by Sultana-Eve** [langx/langx#493]
**Is your feature request related to a problem? Please describe.**
I do not see the empty battery as fitting for no knowledge of a language

**Describe the solution you'd like**
For any romanic languages the empty battery is okay for me, because i atleast know the majority of letters used, but id like to see a crossed trough batter (basically like accu completely dead and turned off) for languages with different sets of letters/pictures/symbols. Like i wanna learn arabic, but i do not even know a single "letter" therefore the empty battery would suggest i at least know the alphabet, where a crossed battered shows "absolutely embrionic"

**Describe alternatives you've considered**
-

**Additional context**
-

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by behics** [comment]
Thank you for rising this issue.

It is interesting @Sultana-Eve . As i understand that you are suggesting a new level of languages.

Which icon you think that for your idea here amount these icons https://ionic.io/ionicons

Thank you

**Comment by Sultana-Eve** [comment]
Hay, i think this one is the most fitting

🚫

внс ***@***.***> schrieb am Mi. 21. Feb. 2024 um 16:31:

**Comment by xuelink** [comment]
```html 
<!-- Absolute Beginner Icon Suggestions -->
<ion-icon name="unlink-outline"></ion-icon>
<ion-icon name="thermometer-outline"></ion-icon>
<ion-icon name="phone-landscape-outline"></ion-icon>

<!-- Advance Icon Suggestions -->
<ion-icon name="rocket-outline"></ion-icon>
```
