### ISSUE TITLE
🐛 [BUG] : Messages that I've already read don't disappear from notifications

### ISSUE THREAD

**Issue by xuelink** [langx/langx#506]
**Describe the bug**
After reading a message, the notification for that message does not disappear. This causes confusion as it appears that there are unread messages when there are not.

**To Reproduce**
1- Read the message and go back to the 'Notifications' page
2- The notification for the read message is still present

**Expected behavior**
After reading a message, the notification for that message should disappear, indicating that there are no unread messages.

**Smartphone (please complete the following information):**
 - All clients

**Additional context**
This issue has been occurring consistently for the past week. Restarting the app and the device does not resolve the issue.

_Contributor: @Yura from Ukraine_

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by behics** [comment]
- [ ] App icon badge counter bug @Sultana-Eve 

![image](https://github.com/languageXchange/languageXchange/assets/3280475/d6bdbc61-2591-4b1a-ad85-c15c8b42fb1e)
