### ISSUE TITLE
🐛 [BUG] : Clear Error after it is shown.

### ISSUE THREAD

**Issue by xuelink** [langx/langx#519]
**Describe the bug**
When the "User not found" button is pressed in the "Profile Visitors" section, a red error is displayed. This error persists and is shown every time the "Community" button is pressed afterwards.

**To Reproduce**
If you press User not found in Profile Visitors you getting red error every time you press Community button

1. Go to 'Profile Visitors'
2. Click on 'User not found'
3. Notice the red error
4. Click on 'Community' button
5. See error

**Expected behavior**
The error should be cleared after it is shown, and should not persist or be shown again when the "Community" button is pressed.

**Screenshots**

https://github.com/languageXchange/languageXchange/assets/3280475/6432fdca-03d0-48e0-900a-405bbca9b923

<img src="https://github.com/languageXchange/languageXchange/assets/3280475/d6ed8090-4371-4fd1-a7c4-92edff848443" alt="Screenshot_20240304-122658" width="300px">

**Additional context**
_Contributor @dev-vaganov_

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by behics** [comment]
@dev-vaganov 
https://github.com/languageXchange/languageXchange/assets/3280475/cb3d0b92-dc3a-4b8a-a83b-47273e8cb62e

**Comment by xuelink** [comment]
It's fixed with RN version.
