### ISSUE TITLE
🐛 [BUG] : Calculation in unseen total message Badge

### ISSUE THREAD

**Issue by xuelink** [langx/langx#526]
**Describe the bug**
The calculation in the unread total message badge is incorrect, showing an inaccurate count of unread messages.

**To Reproduce**
1. Go to the messaging section.
2. Click on any conversation.
3. Receive new messages in multiple conversations.
4. Observe the unread total message badge count.
5. See the error in the displayed count.

**Expected behavior**
The unread total message badge should accurately reflect the total count of unread messages across all conversations.

**Screenshots**

https://github.com/languageXchange/languageXchange/assets/3280475/2dcc3677-8788-43fb-b945-d4fd7bc84c1c

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iphone

**Additional context**
_**Contributor:** @dev-vaganov_

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
Not only within the app but also in the homepage of the app icon shows wrong number! @pastanton

**Comment by pastanton** [comment]
Perhaps a separate bug or feature, but archived chats are adding to the unread messages count as well, without unarchiving. (Not sure what the desired behavior is.)

**Comment by xuelink** [comment]
Before #482 , this issue has been solved!
