### ISSUE TITLE
⚠ : ITMS-91053: Missing API declaration 

### ISSUE THREAD

**Issue by xuelink** [langx/langx#666]
https://www.youtube.com/watch?v=wI2hioco8CY

<img width="751" alt="Screenshot 2024-04-17 at 4 15 03 PM" src="https://github.com/langxapp/langx/assets/3280475/8a5d1620-4491-400e-91c2-d993c82891e9">

**Comment by xuelink** [comment]
@DH-555 do you want me to assign this issue to you ?

**Comment by DH-555** [comment]
Solves the issue: https://github.com/langx/langx/pull/685
