### ISSUE TITLE
🚀 : Edit Message

### ISSUE THREAD

**Issue by pastanton** [langx/langx#687]
**Is your feature request related to a problem? Please describe.**
Messages sent on phones are very error prone. There is no clear and easy way to edit or annotate typos. Typos by native speakers can be detrimental to language learners. 

**Describe the solution you'd like**
The author of a message should be able to edit their message. 

**Describe alternatives you've considered**
Some sort of annotation might be sufficient, which could be combined with a correction feature - allowing a native speaker to correct a language learner, for example.

**Additional context**
This feature is available in many text programs. 

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
@pastanton 
<img width="448" alt="Screenshot 2024-04-21 at 5 38 45 PM" src="https://github.com/langx/langx/assets/3280475/146569db-0881-470d-b88c-d5cedeeab2d9">

**Comment by xuelink** [comment]
@pastanton Or do you mean `correction` instead of `edit` related w/ https://github.com/langx/langx/issues/484
