### ISSUE TITLE
🐛 : Edit profile picture button does not work as expected

### ISSUE THREAD

**Issue by angr-pukhlya** [langx/langx#744]
**Describe the bug**
i wanted to change profile picture from default to something different. i tapped "edit", but nothing happened.

**To Reproduce**
1. Go to Profile section
2. Click on Edit button
3. Tap on "edit" button in the "Profile Picture" section

**Expected behavior**
A pop-up asking for permission to access pictures from devise should show up first. After granting permission, a pop-up with option to choose picture from a phone should open.

**Smartphone (please complete the following information):**
 - Device: Galaxy A22 5G
 - OS: Android
 - Version 13

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
Reported again with this model: ![image](https://github.com/langx/langx/assets/3280475/e8ccc144-eab1-4c8f-8c56-4b01c32c2eab)

i am going to find the same device simulator and check the logs

**Comment by xuelink** [comment]
@Aboud202 from #747 

Describe the bug:
I wanted to change profile picture from default to another, I tapped / Edit/, but nothing happened.

To Reproduce
Steps to reproduce the behavior:

Go to Profile section
Click on Edit button
Tap on "edit" button in the (Profile Picture")
section
Or tapping on (Add) in 
(Other pictures) Section 

https://github.com/langx/langx/assets/170677858/2dd3dace-8988-4ada-96e9-6f2bd35f3701
