### ISSUE TITLE
⚠ : anything connected with a dot becomes a link

### ISSUE THREAD

**Issue by Sultana-Eve** [langx/langx#774]
**Is your warning request related to a problem? Please describe.**
anything that is connected with a dot, like test.test becomes a clickable link.

**Describe the solution you'd like**
make links not working/non-existing

**Describe alternatives you've considered**
-

**Additional context**
this gives the potential to link whatever you want
from pornside to downloadable malware and racism-related sites, many of these are illegal in several countries or at least age restricted. Our community is not only 18+, the advantege of one person in 1000 is not worth the risk of making our app an exchange-platform for bad-shareware and illegal websites

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
https://github.com/langx/langx/blob/868305c02f522177de979bbc9f9ebe3f2c4b0650/src/app/extras/utils.ts#L206

**Comment by Sultana-Eve** [comment]
contradicting #613

**Comment by xuelink** [comment]
To create a more comprehensive regex that accounts for all current TLDs while avoiding issues with non-URLs like `test.test`, you can update the regex to only match known TLDs. Here is a simplified approach that uses a common set of TLDs to start with, and you can expand it as needed:

### Updated Regular Expression

```javascript
var urlRegex = /(\b(https?:\/\/)?[a-z0-9]+([-.][a-z0-9]+)*\.(com|org|net|edu|gov|mil|int|co|io|info|biz|online|tech|xyz|app|site|club|dev|shop|store|media|tv|live|me|world|space|guru|today|news|digital|website|cloud|global|solutions|services|community|technology|systems|company|support|management|international|academy|school|email|finance|ventures|capital|partners|group|consulting|agency|events|gallery|marketing|design|photography|press|publishing)([-a-z0-9@:%_+.~#?&//=]*)?\b)/gi;
```

### Explanation:

1. **Protocol:** `(https?:\/\/)?`
   - Optionally matches `http://` or `https://`.

2. **Domain Name:** `[a-z0-9]+([-.][a-z0-9]+)*`
   - Matches the domain name which can contain letters, numbers, hyphens, and dots.

3. **TLDs:** `\.(com|org|net|edu|gov|mil|int|co|io|info|biz|online|tech|xyz|app|site|club|dev|shop|store|media|tv|live|me|world|space|guru|today|news|digital|website|cloud|global|solutions|services|community|technology|systems|company|support|management|international|academy|school|email|finance|ventures|capital|partners|group|consulting|agency|events|gallery|marketing|design|photography|press|publishing)`
   - Matches only the specified top-level domains.

4. **Path:** `([-a-z0-9@:%_+.~#?&//=]*)?`
   - Optionally matches a path that can include a variety of characters.
