### ISSUE TITLE
🚀 : Replacement emoji for Esperanto

### ISSUE THREAD

**Issue by Malenaiuannabluu** [langx/langx#830]
Because Esperanto's official flag has not been made into an emoji, it would be ideal to find a replacement as all languages use their respective emoji's to represent them. 

Because Esperanto's official flag has a star on it, I think that the replacement emoji should be a ⭐. There should also be a one time only pop up announcement that appears to both app and web users when they open the app to the update that would expain why the star emoji will appear(I can work on writing this if needed :D)

**Comment by xuelink** [comment]
Thank you @Malenaiuannabluu

**Comment by xuelink** [comment]
![IMG_1885](https://github.com/langx/langx/assets/3280475/faba252f-084c-42e2-b6c3-76674f70430a)

**Comment by xuelink** [comment]
<img width="699" alt="Screenshot 2024-06-22 at 3 36 34 PM" src="https://github.com/langx/langx/assets/3280475/11bb2243-757d-41ac-8f5e-b78f4b9f59a8">

**Comment by xuelink** [comment]
Fixed w/ https://github.com/langx/langx-react-native/commit/9b495aefa92f9f855d72a32e22869767af552a39 

Related file: https://github.com/langx/langx-react-native/commit/9b495aefa92f9f855d72a32e22869767af552a39#diff-fe27bd1959a71d855a638abc75c5970c9b04134f35063298eb1ef47660621814
