### ISSUE TITLE
🐛 : User not found issue

### ISSUE THREAD

**Issue by Malenaiuannabluu** [langx/langx#831]
Sometimes when looking at chats(both chat list and dms) users appear as deleted accounts(user not found)

Did not occur when using website browser but appeared twice on ios app

![image](https://github.com/langx/langx/assets/172441661/6d808e29-38e8-4a3e-b369-b0a6bce13a8a)

**Comment by xuelink** [comment]
Thank you for rising that issue. It should be investgated!

**Comment by Malenaiuannabluu** [comment]
> Thank you for rising that issue. It should be investgated!

Another thing to be aware of is that you can't send messages to the account either and the account becomes exactly like one that is actually deleted!! I couldn't send you any messages and I was confused until I looked up XD

**Comment by xuelink** [comment]
Rooms has a member of "deleted-users"  will not be visible anymore and deleted for both sender and receiver.
