### ISSUE TITLE
🚀 : Use more generic font for chat messages in the rooms instead of `Comfortaa`

### ISSUE THREAD

**Issue by xuelink** [langx/langx#869]
**Is your feature request related to a problem? Please describe.**
While messaging, comfortaa font may not be the good option.

**Describe the solution you'd like**
We can use this one at the same time: https://fonts.google.com/specimen/Lexend

**Contributor**
<img width="452" alt="Screenshot 2024-06-30 at 5 02 46 AM" src="https://github.com/langx/langx/assets/3280475/7405a089-dd33-4078-b8c1-2dfc31addb73">
<img width="468" alt="Screenshot 2024-06-30 at 5 02 50 AM" src="https://github.com/langx/langx/assets/3280475/cc1b20f8-1276-45e5-b4da-50a44366d7f5">

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by daddydave** [comment]
Agreed, and I am the kind of person who expects the font  to look like something already installed on the phone, otherwise the app looks a bit out of place.

**Comment by xuelink** [comment]
https://fonts.google.com/noto

**Comment by xuelink** [comment]
- [ ] Load only used fonts.

**Comment by xuelink** [comment]
Closed w/ 5a3b80c3ba0a3ea1e0572c05332294a41af0afe5 and 022ae30a09e2565edc24a8990397d1301e368eea

We have now 3 different fonts available. https://github.com/langx/langx/tree/main/assets/fonts
