### ISSUE TITLE
🚀 : Support for more alphabets (ex. ukranian/russian)

### ISSUE THREAD

**Issue by Honzoraptor31415** [langx/langx#896]
**Is your feature request related to a problem? Please describe.**
Yes; the current problem is, that you can't comfortably read and write anything in the app that uses a language with a specific alphabet, for example ukranian. I think what causes this is the custom font all of the apps use as of now.

**Describe the solution you'd like**
Get a different font or find a version that supports alphabets like the ukranian one.

**Comment by xuelink** [comment]
Thank you for your rising up this issue.

Related #566 

and fixed with https://github.com/langx/langx/issues/869 

It will be available with the next release.
